### PR TITLE
Update docs to use RTD

### LINKED ISSUE #1: Improved user operation and installation guides with github pages
This task is to generate github pages for the user guide using favorite Python docs generator.

- [x] Deploy pds-deep-archive to pypi for easy install
- [x] Dependencies/Assumptions  - e.g. python3 must be installed
- [x] Installation Guide - let's start with buildout instructions then have alternative instructions using virtualenv since most of our users will not be able to do that
- [x] Operation Guide - very basic "this is how you run it" with an output of `-h`

### LINKED ISSUE #2: Implement SIP generation offline capabilities
Formal requirements to come (#3), but for now, we need to get something together to accomplish this.

Informal requirements:
1. Software shall produce SIP Manifest table (and eventually AIP manifest (#2)) with accompanying label
2. The SIP Manifest should be a tab-separated 4 column manifest table with columns, checksum, checksum_type, file_specification_url, LIDVID (see example ladee_mission_bundle_SIP_4col_manifest_v1.0.xml and ladee_mission_bundle_SIP_4col_manifest_v1.0.tab in attached .zip)
3. A user will input a bundle directory, and the software will read the bundle.xml at the top level of the bundle. The software then proceed to query the registry for all *primary* products associated with that bundle (using the bundle lidvid) (not sure if this is possible, if not. we may need to parse all the collection lidvids/lids from the bundle.xml and use those to query the registry).
4. From the registry output, we should parse the necessary fields to populate the SIP Manifest.
5. More to come...

Use https://pds-dev-el7.jpl.nasa.gov/services/registry/pds/select?q=*%3A* for testing.

Example Python implementation, SIP/AIP products, templates, etc: [aaaZip_NSSDC_20190820.zip](https://github.jpl.nasa.gov/PDSEN/aip-gen/files/5301/aaaZip_NSSDC_20190820.zip)
Test bundle: https://atmos.nmsu.edu/PDS/data/PDS4/LADEE/mission_bundle/ (fixed URL)

### PR DESCRIPTION
**Pull request by jordanpadams**
updates include:
* switchover to using RTD theme
* add architecture diagram for different tool usage

### CODE REVIEW

**Comment by jordanpadams** [comment]
@nutjob4life can you take a look at this and update so that it works 😟 . i somehow had a `build/docs/Makefile` to generate the docs, but then ran `make clean` and it disappeared and i forget what I need to do in order to get it back to generate the docs.

**Comment by nutjob4life** [comment]
@jordanpadams this worked for me:
```console
$ sw_vers
ProductName:	macOS
ProductVersion:	11.3.1
BuildVersion:	20E241
$ python --version
Python 3.9.2
$ cd /tmp
$ git clone git@github.com:NASA-PDS/pds-deep-archive.git
$ cd pds-deep-archive
gh pr checkout 108
Switched to a new branch 'doc_updates'
$ python3 -m venv venv
$ venv/bin/pip install --quiet setuptools==51.3.3
$ venv/bin/python3 bootstrap.py --allow-site-packages
$ bin/buildout
$ bin/docbuilder
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] usage/index                                                                                    
generating indices... genindex
writing additional pages... search
copying images... [100%] _static/images/fs-vs-registry.png                                                              
copying static files... WARNING: logo file 'images/PDS_Planets.png' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.

The HTML pages are in html.
```

The `bin/docbuilder` script just does `cd build/docs; make html` so the `Makefile` definitely gets regenerated.

**Review by nutjob4life — APPROVED** [review]
🛳 it!

**Comment by jordanpadams** [comment]
thanks @nutjob4life . i couldn't get it to work in my environment but that is fine. i will create another ticket to retrofit this repo per the new template repo.

**Comment by jordanpadams** [comment]
@nutjob4life could you actually take a look at the generated docs and make sure the logo and diagram actually appear correctly? looks like the logo I specified in the conf.py may be an incorrect path

**Comment by nutjob4life** [comment]
@jordanpadams will do!

**Pull request merged**
